### ISSUE TITLE
Input File for CelFEER

### ISSUE THREAD

**Issue by NichKu** [pi-zz-a/CelFEER#1]
Great work!
Are you also planning to upload a script to generate the input file for celfeer.py?

**Comment by pi-zz-a** [comment]
Hi @NichKu , thank you, I can definitely do that. I will get back to you!

**Comment by pi-zz-a** [comment]
@NichKu it is not entirely clear for me what you are asking for. Are you asking for the full pipeline from fastq files to read counts?

**Comment by NichKu** [comment]
Thanks for your response.
If you can provide that it would be very helpful!
If not, then I would just appreciate the code you used to create the file with the read methylation percentage in the 500bp windows from e.g. a bam file.
The marker file you uploaded is only for chromosome 1. Would you mind providing the full marker file you used for the ALS cfDNA data (the one you used for intersecting with the cfDNA data)?

**Comment by pi-zz-a** [comment]
Hi @NichKu , I provided the complete file of ALS markers we found, and provided a guide on how to process read data, as well as some scripts, both of which you can find in scripts/data_processing. Unfortunately I don't have a streamlined workflow to provide you.

**Comment by NichKu** [comment]
Thanks a lot!
It works, really appreciate it.
